# Generated by Django 4.2.7 on 2023-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviews',
            field=models.ManyToManyField(null=True, related_name='guests', to='reviews.review'),
        ),
    ]
