# Generated by Django 4.2.7 on 2023-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('RG', 'Rg'), ('CPF', 'Cpf'), ('PASSAPORTE', 'Passaporte'), ('OUTRO', 'Outro')], default='CPF', max_length=10),
        ),
    ]
