# Generated by Django 4.2.7 on 2023-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviews',
            field=models.ManyToManyField(related_name='guests', to='reviews.review'),
        ),
    ]
