# Generated by Django 4.2.7 on 2023-11-11 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('promotions', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(3, 'Three'), (4, 'Four'), (5, 'Five')], default=3)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('promotions', models.ManyToManyField(related_name='hotels', to='promotions.promotion')),
                ('reviews', models.ManyToManyField(related_name='hotels', to='reviews.review')),
                ('services', models.ManyToManyField(related_name='hotels', to='services.service')),
            ],
        ),
    ]
