# Generated by Django 4.2.7 on 2023-11-11 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(3, 'Three'), (4, 'Four'), (5, 'Five')], default=3)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.TextField()),
            ],
        ),
    ]
