# Generated by Django 4.2.7 on 2023-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('services', '0001_initial'),
        ('reviews', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='promotions',
            field=models.ManyToManyField(null=True, related_name='hotels', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reviews',
            field=models.ManyToManyField(null=True, related_name='hotels', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(null=True, related_name='hotels', to='services.service'),
        ),
    ]
