# Generated by Django 4.2.7 on 2023-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('promotions', '0001_initial'),
        ('services', '0001_initial'),
        ('hotels', '0002_alter_hotel_promotions_alter_hotel_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='promotions',
            field=models.ManyToManyField(related_name='hotels', to='promotions.promotion'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reviews',
            field=models.ManyToManyField(related_name='hotels', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(related_name='hotels', to='services.service'),
        ),
    ]
