# Generated by Django 4.2.7 on 2023-11-11 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Cancelada', 'Cancelada')], default='Confirmado', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('payments_methods', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Débito', 'Debito'), ('Crédito', 'Credito')], max_length=8, null=True)),
                ('total', models.FloatField()),
            ],
        ),
    ]
