# Generated by Django 4.2.7 on 2023-11-10 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('limpo', 'Limpo'), ('ocupado', 'Ocupado'), ('manutenção', 'Manutencao'), ('disponível', 'Disponivel')], default='disponível', max_length=10)),
                ('room_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
