# Generated by Django 4.2.7 on 2023-11-11 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('limpo', 'Limpo'), ('ocupado', 'Ocupado'), ('manutenção', 'Manutencao'), ('disponível', 'Disponivel')], default='disponível', max_length=10)),
                ('room_type', models.CharField(max_length=20)),
                ('bed_number', models.IntegerField(default=2)),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedrooms', to='hotels.hotel')),
            ],
        ),
    ]
